# Generated by Django 5.1.1 on 2025-05-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0002_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Take'), ('online', 'Online Payment')], default='cash', max_length=10),
        ),
    ]
