# Generated by Django 5.1.1 on 2025-05-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Take'), ('online', 'Online Payment')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED YOUR ORDER', 'Accepted your order'), ('REJECTED YOUR ORDER', 'Rejected your order'), ('PREPARING', 'Preparing'), ('READY FOR TAKE', 'Ready for take')], default='PENDING', max_length=30),
        ),
    ]
